name: Tests
on: push
jobs:
  tests:
    runs-on: ubunto-latest
    if:"!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: pnpm install 
      - name: tests
        run: pnpm test
